const customers = [
    {
        id: 1,
        name: "Riya Patel",
        email: "riya.patel@example.com",
        membership: "Free",
        avatar: "https://randomuser.me/api/portraits/women/1.jpg",
        joinDate: "2024-01-05",
    },
    {
        id: 2,
        name: "Arjun Mehta",
        email: "arjun.mehta@example.com",
        membership: "VIP",
        avatar: "https://randomuser.me/api/portraits/men/2.jpg",
        joinDate: "2024-01-18",
    },
    {
        id: 3,
        name: "Kavya Sharma",
        email: "kavya.sharma@example.com",
        membership: "Premium",
        avatar: "https://randomuser.me/api/portraits/women/3.jpg",
        joinDate: "2024-02-01",
    },
    {
        id: 4,
        name: "Deepak Verma",
        email: "deepak.verma@example.com",
        membership: "Gold",
        avatar: "https://randomuser.me/api/portraits/men/4.jpg",
        joinDate: "2024-02-15",
    },
    {
        id: 5,
        name: "Priya Singh",
        email: "priya.singh@example.com",
        membership: "Free",
        avatar: "https://randomuser.me/api/portraits/women/5.jpg",
        joinDate: "2024-03-02",
    },
    {
        id: 6,
        name: "Rahul Tiwari",
        email: "rahul.tiwari@example.com",
        membership: "VIP",
        avatar: "https://randomuser.me/api/portraits/men/6.jpg",
        joinDate: "2024-03-10",
    },
    {
        id: 7,
        name: "Aisha Khan",
        email: "aisha.khan@example.com",
        membership: "Premium",
        avatar: "https://randomuser.me/api/portraits/women/7.jpg",
        joinDate: "2024-03-25",
    },
    {
        id: 8,
        name: "Sanjay Kumar",
        email: "sanjay.kumar@example.com",
        membership: "Free",
        avatar: "https://randomuser.me/api/portraits/men/8.jpg",
        joinDate: "2024-04-11",
    },
    {
        id: 9,
        name: "Nandini Rao",
        email: "nandini.rao@example.com",
        membership: "Gold",
        avatar: "https://randomuser.me/api/portraits/women/9.jpg",
        joinDate: "2024-04-20",
    },
    {
        id: 10,
        name: "Vikram Reddy",
        email: "vikram.reddy@example.com",
        membership: "VIP",
        avatar: "https://randomuser.me/api/portraits/men/10.jpg",
        joinDate: "2024-05-01",
    },
    {
        id: 11,
        name: "Anjali Dubey",
        email: "anjali.dubey@example.com",
        membership: "Premium",
        avatar: "https://randomuser.me/api/portraits/women/11.jpg",
        joinDate: "2024-05-15",
    },
    {
        id: 12,
        name: "Gaurav Singh",
        email: "gaurav.singh@example.com",
        membership: "Free",
        avatar: "https://randomuser.me/api/portraits/men/12.jpg",
        joinDate: "2024-06-03",
    },
    {
        id: 13,
        name: "Simran Kaur",
        email: "simran.kaur@example.com",
        membership: "Gold",
        avatar: "https://randomuser.me/api/portraits/women/13.jpg",
        joinDate: "2024-06-19",
    },
    {
        id: 14,
        name: "Rohit Deshmukh",
        email: "rohit.deshmukh@example.com",
        membership: "VIP",
        avatar: "https://randomuser.me/api/portraits/men/14.jpg",
        joinDate: "2024-07-01",
    },
    {
        id: 15,
        name: "Meera Iyer",
        email: "meera.iyer@example.com",
        membership: "Free",
        avatar: "https://randomuser.me/api/portraits/women/15.jpg",
        joinDate: "2024-07-14",
    },
    {
        id: 16,
        name: "Vivek Bansal",
        email: "vivek.bansal@example.com",
        membership: "Premium",
        avatar: "https://randomuser.me/api/portraits/men/16.jpg",
        joinDate: "2024-08-01",
    },
    {
        id: 17,
        name: "Sheela Menon",
        email: "sheela.menon@example.com",
        membership: "Gold",
        avatar: "https://randomuser.me/api/portraits/women/17.jpg",
        joinDate: "2024-08-18",
    },
    {
        id: 18,
        name: "Kiran Joshi",
        email: "kiran.joshi@example.com",
        membership: "Free",
        avatar: "https://randomuser.me/api/portraits/men/18.jpg",
        joinDate: "2024-09-05",
    },
    {
        id: 19,
        name: "Preeti Shah",
        email: "preeti.shah@example.com",
        membership: "VIP",
        avatar: "https://randomuser.me/api/portraits/women/19.jpg",
        joinDate: "2024-09-22",
    },
    {
        id: 20,
        name: "Manish Aggarwal",
        email: "manish.aggarwal@example.com",
        membership: "Premium",
        avatar: "https://randomuser.me/api/portraits/men/20.jpg",
        joinDate: "2024-10-01",
    },
];

export default customers;
